grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
      - 3000:3000
    volumes:
      - /srv/docker/grafana/data:/var/lib/grafana

portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /srv/docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
